"use client";

import React from "react";
import { Sparkles, CheckCircle2, ShieldCheck } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface AiSummaryCardProps {
  summaryPoints: string[];
  toxicityScore?: number;
}

export function AiSummaryCard({ summaryPoints, toxicityScore = 0.02 }: AiSummaryCardProps) {
  return (
    <Card className="border-purple-500/20 bg-purple-950/10 backdrop-blur shadow-sm">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Badge variant="ai" className="gap-1.5 px-2.5 py-0.5">
              <Sparkles className="h-3.5 w-3.5" /> AI KEY TAKEAWAYS
            </Badge>
            <span className="text-xs text-muted-foreground">Generated by AI Editorial Engine</span>
          </div>
          <Badge variant="outline" className="gap-1 text-emerald-400 border-emerald-500/30 text-xs">
            <ShieldCheck className="h-3 w-3" /> Toxicity Clean ({(toxicityScore * 100).toFixed(1)}%)
          </Badge>
        </div>
        <CardTitle className="text-lg font-bold pt-1">Executive Summary</CardTitle>
      </CardHeader>
      <CardContent>
        <ul className="space-y-2.5">
          {summaryPoints.map((point, index) => (
            <li key={index} className="flex items-start gap-2.5 text-sm leading-relaxed">
              <CheckCircle2 className="h-4 w-4 text-purple-400 shrink-0 mt-0.5" />
              <span>{point}</span>
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  );
}
