#!/usr/bin/env bash
# Pull the public browser configuration of the Next.js apps from OpenBao
# (mount `edition`, key `frontend`) and write it to apps/<app>/.env.local.
#
# OpenBao is populated by Edition-terraform on every apply: the Firebase web
# config is read from the Firebase Management API (module.firebase_auth) and
# seeded into edition/frontend by the in-cluster bootstrap Job.
#
# Requirements: kubectl pointed at the cluster (Edition-terraform: `make kubeconfig`).
# Auth: $BAO_TOKEN if exported, otherwise the root token from the openbao-init Secret.
#
#   pnpm env:pull                 # all apps
#   pnpm env:pull -- admin cms-studio
#   OPENBAO_KEY=frontend pnpm env:pull
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NS="${OPENBAO_NS:-openbao}"
POD="${OPENBAO_POD:-openbao-0}"
MOUNT="${OPENBAO_MOUNT:-edition}"
KEY="${OPENBAO_KEY:-frontend}"
ENV_FILE="${ENV_FILE:-.env.local}"

# Only these keys are written: everything the browser bundle may see, plus the
# server-side API URL. Anything else in the OpenBao path is ignored on purpose.
ALLOWED='^(NEXT_PUBLIC_[A-Z0-9_]+|INTERNAL_API_URL)$'

if [ $# -gt 0 ]; then
  APPS=("$@")
else
  APPS=()
  for d in "$ROOT"/apps/*/; do APPS+=("$(basename "$d")"); done
fi

command -v kubectl >/dev/null || { echo "kubectl not found" >&2; exit 1; }

if [ -z "${BAO_TOKEN:-}" ]; then
  BAO_TOKEN="$(kubectl -n "$NS" get secret openbao-init -o jsonpath='{.data.root_token}' 2>/dev/null | base64 -d || true)"
  [ -n "$BAO_TOKEN" ] || { echo "no BAO_TOKEN and no openbao-init Secret in namespace $NS (run: make kubeconfig in Edition-terraform)" >&2; exit 1; }
fi

echo "Reading $MOUNT/$KEY from OpenBao ($NS/$POD)..." >&2
JSON="$(kubectl -n "$NS" exec -i "$POD" -- env "BAO_TOKEN=$BAO_TOKEN" bao kv get -format=json -mount="$MOUNT" "$KEY")"

# KEY=VALUE lines, sorted, filtered to the allow-list. Values are quoted for dotenv.
LINES="$(printf '%s' "$JSON" | python3 -c '
import json, re, sys
allowed = re.compile(sys.argv[1])
data = json.load(sys.stdin)["data"]["data"]
for k in sorted(data):
    if allowed.match(k):
        v = str(data[k]).replace("\\", "\\\\").replace("\"", "\\\"")
        print(f"{k}=\"{v}\"")
' "$ALLOWED")"

[ -n "$LINES" ] || { echo "no NEXT_PUBLIC_* keys found in $MOUNT/$KEY" >&2; exit 1; }

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
VERSION="$(printf '%s' "$JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["metadata"]["version"])')"

for app in "${APPS[@]}"; do
  dir="$ROOT/apps/$app"
  [ -d "$dir" ] || { echo "skip $app: no such app" >&2; continue; }
  {
    echo "# Generated by scripts/env-from-openbao.sh from OpenBao $MOUNT/$KEY (version $VERSION) at $STAMP."
    echo "# Do not edit by hand; re-run \`pnpm env:pull\`. Git-ignored."
    echo "$LINES"
  } > "$dir/$ENV_FILE"
  chmod 600 "$dir/$ENV_FILE"
  echo "wrote apps/$app/$ENV_FILE ($(echo "$LINES" | wc -l | tr -d ' ') keys)" >&2
done
